language: r
cache: packages
addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      - libudunits2-dev

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

r_packages:
  - covr
after_success:
  - Rscript -e 'library(covr);codecov()'

warnings_are_errors: false
