language: r
cache: packages
warnings_are_errors: false

r:
  - oldrel
  - release
  - devel

r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual --timings

addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      - libudunits2-dev
      - libharfbuzz-dev
      - libfribidi-dev

sudo: required
services:
  - xvfb

before_install:
    - export DISPLAY=:99.0
    - export RGL_USE_NULL=TRUE

script: 
  - |
    R CMD build .
    travis_wait 40 R CMD check windfarmGA*tar.gz

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr);codecov(quiet = FALSE)'

notifications:
  email:
    on_success: change
    on_failure: change

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
