language: r
cache: packages
warnings_are_errors: false
addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      - libudunits2-dev

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - export RGL_USE_NULL=TRUE
 
r_packages:
  - covr
after_success:
  - Rscript -e 'library(covr);codecov()'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master