language: r
cache: packages
addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev

r_packages:
  - covr
after_success:
  - Rscript -e 'library(covr);codecov()'

warnings_are_errors: true
