---
title: "Optimization with Rectangular Grids"
author: "Sebastian Gatscha"
date: "26.07.2019"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This vignette shows how to run a windfarm optimization with rectangular grid cells. 
It needs:

- An area as Shapefile / Simple Feature / Data.frame or Matrix
- A data.frame with wind speed / direction information


## Code

```{r, eval=FALSE}
library(sp)
library(windfarmGA)
Polygon1 <- Polygon(rbind(c(4498482, 2668272), c(4498482, 2669343),
                          c(4499991, 2669343), c(4499991, 2668272)))
Polygon1 <- SpatialPolygons(list(Polygons(list(Polygon1), 1)))
Projection <- "+proj=laea +lat_0=52 +lon_0=10 +x_0=4321000 +y_0=3210000
+ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"
proj4string(Polygon1) <- CRS(Projection)

data.in <- data.frame(ws = 12, wd = 0)

result <- genetic_algorithm(Polygon1 = Polygon1,
                  n = 12,
                  vdirspe = data.in,
                  Rotor = 30,
                  RotorHeight = 100)
```
