// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rotate_CPP
NumericMatrix rotate_CPP(NumericVector X1, NumericVector Y1, double Px, double Py, float angle);
RcppExport SEXP _windfarmGA_rotate_CPP(SEXP X1SEXP, SEXP Y1SEXP, SEXP PxSEXP, SEXP PySEXP, SEXP angleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y1(Y1SEXP);
    Rcpp::traits::input_parameter< double >::type Px(PxSEXP);
    Rcpp::traits::input_parameter< double >::type Py(PySEXP);
    Rcpp::traits::input_parameter< float >::type angle(angleSEXP);
    rcpp_result_gen = Rcpp::wrap(rotate_CPP(X1, Y1, Px, Py, angle));
    return rcpp_result_gen;
END_RCPP
}
// energy_calc_CPP
double energy_calc_CPP(NumericVector wind_speed, NumericVector rotor_radius, NumericVector air_rh);
RcppExport SEXP _windfarmGA_energy_calc_CPP(SEXP wind_speedSEXP, SEXP rotor_radiusSEXP, SEXP air_rhSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type wind_speed(wind_speedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rotor_radius(rotor_radiusSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type air_rh(air_rhSEXP);
    rcpp_result_gen = Rcpp::wrap(energy_calc_CPP(wind_speed, rotor_radius, air_rh));
    return rcpp_result_gen;
END_RCPP
}
// circle_intersection_CPP
NumericVector circle_intersection_CPP(NumericVector r1, NumericVector r2, NumericVector h1, NumericVector h2, NumericVector dx);
RcppExport SEXP _windfarmGA_circle_intersection_CPP(SEXP r1SEXP, SEXP r2SEXP, SEXP h1SEXP, SEXP h2SEXP, SEXP dxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type r1(r1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r2(r2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type h1(h1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type h2(h2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dx(dxSEXP);
    rcpp_result_gen = Rcpp::wrap(circle_intersection_CPP(r1, r2, h1, h2, dx));
    return rcpp_result_gen;
END_RCPP
}
// get_dist_angles_CPP
NumericMatrix get_dist_angles_CPP(NumericMatrix t, int o, double wnkl, double dist);
RcppExport SEXP _windfarmGA_get_dist_angles_CPP(SEXP tSEXP, SEXP oSEXP, SEXP wnklSEXP, SEXP distSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type o(oSEXP);
    Rcpp::traits::input_parameter< double >::type wnkl(wnklSEXP);
    Rcpp::traits::input_parameter< double >::type dist(distSEXP);
    rcpp_result_gen = Rcpp::wrap(get_dist_angles_CPP(t, o, wnkl, dist));
    return rcpp_result_gen;
END_RCPP
}
// turbine_influences_CPP
List turbine_influences_CPP(NumericMatrix t, double wnkl, double dist, double dirct);
RcppExport SEXP _windfarmGA_turbine_influences_CPP(SEXP tSEXP, SEXP wnklSEXP, SEXP distSEXP, SEXP dirctSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type wnkl(wnklSEXP);
    Rcpp::traits::input_parameter< double >::type dist(distSEXP);
    Rcpp::traits::input_parameter< double >::type dirct(dirctSEXP);
    rcpp_result_gen = Rcpp::wrap(turbine_influences_CPP(t, wnkl, dist, dirct));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_windfarmGA_rotate_CPP", (DL_FUNC) &_windfarmGA_rotate_CPP, 5},
    {"_windfarmGA_energy_calc_CPP", (DL_FUNC) &_windfarmGA_energy_calc_CPP, 3},
    {"_windfarmGA_circle_intersection_CPP", (DL_FUNC) &_windfarmGA_circle_intersection_CPP, 5},
    {"_windfarmGA_get_dist_angles_CPP", (DL_FUNC) &_windfarmGA_get_dist_angles_CPP, 4},
    {"_windfarmGA_turbine_influences_CPP", (DL_FUNC) &_windfarmGA_turbine_influences_CPP, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_windfarmGA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
