# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rotate_CPP <- function(X1, Y1, Px, Py, angle) {
    .Call(`_windfarmGA_rotate_CPP`, X1, Y1, Px, Py, angle)
}

angles_CPP <- function(Aa, Bb, Cc) {
    .Call(`_windfarmGA_angles_CPP`, Aa, Bb, Cc)
}

energy_calc_CPP <- function(wind_speed, rotor_radius, air_rh) {
    .Call(`_windfarmGA_energy_calc_CPP`, wind_speed, rotor_radius, air_rh)
}

euc_CPP <- function(x1, x2, y1, y2) {
    .Call(`_windfarmGA_euc_CPP`, x1, x2, y1, y2)
}

point_2_line_CPP <- function(x, y) {
    .Call(`_windfarmGA_point_2_line_CPP`, x, y)
}

circle_intersection_CPP <- function(r1, r2, h1, h2, dx) {
    .Call(`_windfarmGA_circle_intersection_CPP`, r1, r2, h1, h2, dx)
}

get_dist_angles_CPP <- function(t, o, wnkl, dist) {
    .Call(`_windfarmGA_get_dist_angles_CPP`, t, o, wnkl, dist)
}

turbine_influences_CPP <- function(t, wnkl, dist, dirct) {
    .Call(`_windfarmGA_turbine_influences_CPP`, t, wnkl, dist, dirct)
}

