# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

wake <- function(Rotorf, wakr, leA) {
    .Call(`_windfarmGA_wake`, Rotorf, wakr, leA)
}

wakeRcpp <- function(lenght_b, topograp, RotD, k) {
    .Call(`_windfarmGA_wakeRcpp`, lenght_b, topograp, RotD, k)
}

